language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: virogenesis
  password:
    secure: QiBvilK8188P96sudNIQkcSoDqAyhC0RkYU3UgUQyIxDibkyEP+P2kIoEcgOBf54xHGWspOyHYuH8qdLPB4FbBQyHhzOTF7wy98/rFc7I8Btg1EWyIC3qC37ao0+SOAkGue/ytuoZ26yb6eoLImyfeuAFrRCSc4IK6MNammFe0EqdYOhlUZy+CsSQBR29jxcN5C3dP1CiQfXGhfkXeXp4HtqTKf5dlbBssQKwB6wJcqJNz+r0YdmlOpr1JtR8RBGXpOTjXOHc8P6t00Vw93fZYsUm40uKYni5PTI0Z+O5TGSLll60kHV9d53etS6Q2vyh9fw+44haBzA4Ohnh+CV0qyru2ErjCS4d2IWM4P0A1xfwiQdvGvmiz3kpdQ+6ODgH0GkEEe4EIefEzVKRrWX15TlNUDXKltK1WrmXBRBL+qjvZ2NsNxM3wSUFzgrc2oqLw2vtQPNwsowLnoAKZRmwWbsUfT0hjFzQe576L5xub2UaO9MAtoGVqz+4UNH2mz7u1Mgjh5hOcrb+Lzr3T0oYPsBSNZfYlCHvD9QkjKp4S8IealN81UtEVLot9EaclbtI7qo/kcmt0YVQ0bqs3e4TayJaJOsL51AN/5QRnEqyTDw3McjNobYN4uR9Ruk8bISSDcmZWsq35sOZGQl2eXKXm4LvQ1IHqom6VRs+1uo12A=
  on:
    tags: true
    repo: virogenesis/port_checker
    python: 3.6
